spring:
  application:
    name: sse-example-service

  config:
    import:
      - classpath:/app/cors/cors.yml

  jpa:
    open-in-view: false # when using jpa with sse

logging:
  level:
    root: info
